### ISSUE TITLE
Better Commands

### ISSUE THREAD

**Issue by Dablakbandit** [Dablakbandit/Bank#1]

**Comment by Tiippex** [comment]
Would suggest to add tab completion for sub commands

**Comment by Dablakbandit** [comment]
@Tiippex 
https://github.com/Dablakbandit/Core/blob/e18414cd6fa3527d1ac0eaa4f51e99fbf08d6dc4/src/main/java/me/dablakbandit/core/commands/AdvancedCommand.java#L131
