### ISSUE TITLE
Access to Money Portion of Bank w/o Commands

### ISSUE THREAD

**Issue by graywolf336** [Dablakbandit/Bank#10]
I would like to force the players on my server to use only the signs (eventually citizens) without having access to the commands. I have granted them `bank.open.sign` but when they use the sign, all of the inventory slots are filled with blacked stained glass panes. But whenever I grant them the permission `bank.money` they can see the money option, however, they also can use the commands.

![2019-03-18_21 07 43](https://user-images.githubusercontent.com/850391/54575432-12d5df00-49c2-11e9-9a6c-409bb9cc0a88.png)

**Comment by Dablakbandit** [comment]
Possibly dont have additional perms?

**Comment by graywolf336** [comment]
What do you mean?

**Comment by Dablakbandit** [comment]
Have you given them the inventory perms from 
https://github.com/Dablakbandit/Bank/wiki/Additional-Permissions

**Comment by graywolf336** [comment]
Yes. They have permission to use the signs and the inventory, but since I took away their ability to use the commands the money portion in the inventory disappeared.

**Comment by Dablakbandit** [comment]
If the inventory is blank it is because they dont have permission to use those inventories, can you check your permissions again?

**Comment by Dablakbandit** [comment]
You can change the command permissions in the commands.yml and give them the permission bank.money back

**Comment by graywolf336** [comment]
That works, thanks!
