### ISSUE TITLE
Config doesn't save with server restart

### ISSUE THREAD

**Issue by LordOmen** [Dablakbandit/Bank#22]
After every server restart, the config.yml reverts to its default settings to include interest rates.

**Comment by LordOmen** [comment]
Yeah this is breaking the economy, because I can't set the amount of tabs with permissions due to the resetting config.yml.  It's also starting to break my economy because of the inability to stop or limit the interest again because of the config resetting.

**Comment by Dablakbandit** [comment]
Has been fixed in beta builds
