### ISSUE TITLE
Placeholders with TitleManager 2.1.3 and Vault1.7.1

### ISSUE THREAD

**Issue by wksjim** [Dablakbandit/Bank#7]
i have installed 
Bank v3.0.9
PlaceholderAPI 2.9.2
TitleManager 2.1.3
Vault1.7.1
in the wiki under Placeholders it bank_money
i have used {bank_money} and %bank_money% nether work
%vault_eco_balance_formatted% works
i am trying to get players bank balance with no luck 
can you help

**Comment by Dablakbandit** [comment]
Sorry for late reply, have you enabled placeholders in config?
